### ISSUE TITLE
Extra newlines before quotes that start with code blocks

### ISSUE THREAD

**Issue by tocic** [knatten/cppquiz23#257]
I was testing the formatting on a local server and found the following strange behaviour:

![image](https://github.com/user-attachments/assets/14ac4bee-9dc9-4f48-b2b0-17d8de2a9e18)

This extra newline is added in cases when we start a quote with a 5-spaced code block (e.g., 284, 297, 339). There's no such problem if the code block is in the middle of a quote (e.g., 323).

If we try to use backticks, e.g.

```
> ```
> R future::get();
> R& future<R&>::get();
> void future<void>::get();
> ```
```
, then there's no newline but the code is not highlighted. It's displayed as a set of individual lines, not a code block:

![image](https://github.com/user-attachments/assets/b48a781d-9557-45df-97b5-62a4bdadb48b)

**Comment by tocic** [comment]
Looks like backticked code blocks are not rendered correctly everywhere, not only in quotes :cry::

![image](https://github.com/user-attachments/assets/03fd3068-a5c1-497f-a370-eec98bc92e03)

We should either fix this problem or replace all the occurrences with 5-spaced code blocks.

**Comment by knatten** [comment]
I agree! I've created https://github.com/knatten/cppquiz/issues/345 for this. I think we should look into that before continuing the porting, instead of going over all the questions again and switching to indentation.
